### ISSUE TITLE
Section Titles & Core Outcomes

### ISSUE THREAD

**Issue by karenword** [data-lessons/instructor-training#11]
Three core outcomes that could be considered as guiding principles for this curriculum are: 

- It’s about THEM. (not you) Empathize (+that may be difficult)
- Teaching is a skill (learned, practiced, and has evidence-based best practices)
- A first tool for your toolbox: (most likely to be 'Slow Down')

Section titles should, alone, convey a narrative consistent with our desired core outcomes. They should also be easy to read, write on a white board, and should accurately apply to all content in the module.

Proposed changes:
**How Learning Works: The Importance of Practice** -> something catchy about skill
**How Learning Works: Expertise and Instruction** -> Expertise and Instruction
**How Learning Works: Working Memory and Cognitive Load** -> Working Memory and Cognitive Load
**Building Teaching Skill: Getting Feedback** -> Building Skill with Feedback
**Creating a Positive Learning Environment: Motivation and Demotivation** -> Motivation and Demotivation
 - recommend separating detailed accessibility content into separate section as it is relevant but not entirely described by motivation. Retain references to motivational importance of minding accessibility.

**Creating a Positive Learning Environment: Mindset** -> 

- recommend merging mindset with motivation, as it really is all about motivation. 

**Building Teaching Skill: The Importance of Practice** -> Teaching is a skill. Let's practice! (or something shorter)
**Building Teaching Skill: Lesson Study** -> whatever it is after this lesson is fixed
**Building Teaching Skill: Live Coding** -> Live Coding
**Building Teaching Skill: Performance Revised** -> Live Coding II
**The Carpentries: Workshop Introductions** -> Starting and Ending a Workshop (with ending content). 
- recommend swapping introductions with Carpentries Teaching Practices, to close out ed content and allow introductions to draw upon logistics info presented in Operations section

**The Carpentries: How We Operate** -> This is fine.  Could be shortened as "Carpentries Operations"
**The Carpentries: Teaching Practices** -> Carpentries Teaching Practices. See above regarding move.
**Afternoon Wrap-Up** -> Create a separate section on Carpentries Instructor Checkout prior to Wrap-up?

**Comment by karenword** [comment]
@ChristinaLK should we consider moving the material on accessibility to Managing a Diverse Classroom now?

**Comment by karenword** [comment]
Title changes proposed for the current update (will also include this in upcoming PR):

How Learning Works: The Importance of Practice -> Skill and Practice
How Learning Works: Expertise and Instruction -> Expertise and Instruction
How Learning Works: Working Memory and Cognitive Load -> Working Memory and Cognitive Load
Building Teaching Skill: Getting Feedback -> Building Skill with Feedback
Creating a Positive Learning Environment: Motivation and Demotivation -> Motivation and Demotivation
Creating a Positive Learning Environment: Mindset -> Mindset
Building Teaching Skill: The Importance of Practice -> Teaching is a Skill
Building Teaching Skill: Live Coding -> Live Coding is a Skill
Building Teaching Skill: Lesson Study -> Lesson Study
Building Teaching Skill: Performance Revised -> Live Coding Round II
(New section: Managing a Diverse Classroom)
The Carpentries: How We Operate -> no changeThe Carpentries: Workshop Introductions -> Workshop Introductions (until/unless adding end-content)
The Carpentries: Teaching Practices -> Putting It Together
(New section: Checkout Process)
Afternoon Wrap-Up -> Wrapping Up

**Comment by raynamharris** [comment]
See #18 for a long discussion of proposed title changes
