### ISSUE TITLE
flagging issues more clearly

### ISSUE THREAD

**Issue by ChristinaLK** [data-lessons/instructor-training#29]
came up in previous discussion: how to flag "high priority" issues (GH sorts by time, which is not ideal) and then communicate that to trainers.  Put in README or CONTRIBUTING.

**Comment by raynamharris** [comment]
What do you want added to the readme or contributing file? Does this related to the instructor training material specifically or does this relate to other DC/SWC lesson repos. This repo don't have a "high priority" label but one could be added

**Comment by ChristinaLK** [comment]
When we were soliciting contributions for the latest push, someone pointed out that there were some good issues for contribution but hard to find because they were on page 2.  I try to tag everything that is ready for a PR as "pr-requested" -- is that good enough and we just need to communicate.  

No need to move on this immediately -- this was just a spot for me to store that piece of feedback for later.
