### ISSUE TITLE
Referencing a Discussion in an issue (test)<!--

### ISSUE THREAD

**Issue by karenword** [data-lessons/instructor-training#46]
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

_Originally posted by @karenword in https://github.com/data-lessons/instructor-training/discussions/44_

**Comment by brownsarahm** [comment]
was this done by converting to an issue?
