### ISSUE TITLE
Current PR to carpentries repo does not include deleting episode on mindset,

### ISSUE THREAD

**Issue by brownsarahm** [data-lessons/instructor-training#53]
it has two episdoes numbered 9.  wasn't the plan to delete 09-mindset because that content is covered elsewhere?

**Comment by karenword** [comment]
So... I think I broke something trying to solve this :( 

I had deleted the file, but I think it was restored by accident during an attempt at resolving conflicts via command-line (I normally use the browser, but it insisted). 

So I deleted the file via direct commit to gh-pages (I know, naughty, but I thought this was a simple error correction!). Now the page build is failing...

**Comment by karenword** [comment]
Solved!
